M48
; DRILL file KiCad 10.0.0 date 2026-04-10T11:10:56
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-04-10T11:10:56+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0453
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0650
%
G90
G05
T1
X1.7084Y1.6148
T2
X0.921Y1.6148
M30
