M48
; DRILL file {KiCad 9.0.8} date 2026-03-21T14:18:03+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-03-21T14:18:03+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0453
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0650
%
G90
G05
T1
X1.7084Y1.6148
T2
X0.921Y1.6148
M30
