# Read flash layout from root CONFIG.h, the single source of project constants.
function(configure_firmware_layout target binary_type image_role)
    if(PICO_SDK_VERSION_STRING VERSION_LESS "2.2.0")
        message(FATAL_ERROR "Pico SDK 2.2.0 or newer is required; set PICO_SDK_PATH.")
    endif()
    foreach(key PICO_FLASH_SIZE_BYTES APP_OFFSET META_OFFSET)
        file(STRINGS "${CMAKE_CURRENT_SOURCE_DIR}/CONFIG.h" definition REGEX "^#define ${key} +0x[0-9a-fA-F]+")
        string(REGEX MATCH "0x[0-9a-fA-F]+" ${key} "${definition}")
        if(NOT ${key})
            message(FATAL_ERROR "Missing numeric ${key} in CONFIG.h")
        endif()
    endforeach()
    if(image_role STREQUAL "application")
        math(EXPR image_origin "0x10000000 + ${APP_OFFSET}" OUTPUT_FORMAT HEXADECIMAL)
        math(EXPR image_length "${PICO_FLASH_SIZE_BYTES} - ${APP_OFFSET}" OUTPUT_FORMAT HEXADECIMAL)
    else()
        set(image_origin 0x10000000)
        set(image_length ${META_OFFSET})
    endif()
    file(READ "${PICO_SDK_PATH}/src/rp2_common/pico_crt0/rp2350/memmap_${binary_type}.ld" linker_text)
    string(REPLACE "INCLUDE \"pico_flash_region.ld\"" "FLASH(rx) : ORIGIN = ${image_origin}, LENGTH = ${image_length}" linker_text "${linker_text}")
    file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/${target}.ld" "${linker_text}")
    pico_set_linker_script(${target} "${CMAKE_CURRENT_BINARY_DIR}/${target}.ld")
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/CONFIG.h")
endfunction()
