<#
.SYNOPSIS
    Generates or updates a BladeCore-M54C (RP2354B) FreeRTOS project.

.DESCRIPTION
    Create mode (default):
        Writes main.c, CONFIG.h, FreeRTOSConfig.h, CMakeLists.txt, pico_sdk_import.cmake,
        build.py, .gitignore, .vscode/, and an empty incl/ folder for user libraries.
        Detects and installs required tools:
            - Git, Python, CMake, Ninja (via winget)
            - Raspberry Pi Pico SDK 2.2.0 (git clone into %USERPROFILE%\.pico-sdk\sdk\2.2.0)
            - ARM GNU Toolchain 14.2.rel1 (download + extract)
            - picotool 2.2.0-a4 + OpenOCD 0.12.0+dev (pico-sdk-tools release)
            - FreeRTOS-Kernel (git clone into project as submodule-like folder)
        Sets PICO_SDK_PATH and PICO_TOOLCHAIN_PATH user env vars.

    Update mode (-Update):
        Rescans incl/ under -TargetPath and rewrites the two marked regions of
        CMakeLists.txt:
            # === USER SOURCES BEGIN === ... # === USER SOURCES END ===
            # === USER INCLUDE DIRS BEGIN === ... # === USER INCLUDE DIRS END ===
        Every .c under incl/ becomes a source. Every subdirectory containing a .h
        becomes an include directory. No other files are touched.

.PARAMETER TargetPath
    Path of the project folder. In create mode it is created if missing. In update
    mode it must be an existing project generated by this script.

.PARAMETER ProjectName
    Create mode only. C identifier used as CMake target and UF2/ELF file name.
    Defaults to the leaf of TargetPath.

.PARAMETER Update
    Update mode. Rewrites the user-managed regions of CMakeLists.txt from the
    current contents of incl/ under -TargetPath. Ignored in create mode.

.PARAMETER SkipToolInstall
    Create mode only. Skip tool detection and installation.

.PARAMETER Force
    Create mode only. Overwrite existing files in TargetPath.

.EXAMPLE
    .\Create_M54C_RTOS.ps1 -TargetPath C:\Dev\MyProject -ProjectName MyProject

.EXAMPLE
    .\Create_M54C_RTOS.ps1 -TargetPath C:\Dev\MyProject -SkipToolInstall

.EXAMPLE
    .\Create_M54C_RTOS.ps1 -TargetPath C:\Dev\MyProject -Update
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true, Position = 0)]
    [string]$TargetPath,

    [Parameter(Position = 1)]
    [string]$ProjectName,

    [switch]$Update,

    [switch]$SkipToolInstall,

    [switch]$Force
)

$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Version pinning: matches the .vscode configuration written below.
# ---------------------------------------------------------------------------
$SDK_VERSION       = '2.2.0'
$TOOLCHAIN_VERSION = '14_2_Rel1'
$PICOTOOL_VERSION  = '2.2.0-a4'
$OPENOCD_VERSION   = '0.12.0+dev'
$CMAKE_VERSION     = 'v3.31.5'
$NINJA_VERSION     = 'v1.12.1'

$PICO_SDK_TOOLS_TAG   = 'v2.2.0-2'  # pico-sdk-tools release providing picotool + openocd for Windows
$FREERTOS_KERNEL_REPO = 'https://github.com/raspberrypi/FreeRTOS-Kernel.git'
$FREERTOS_KERNEL_BRANCH = 'main'  # raspberrypi/FreeRTOS-Kernel main has portable/ThirdParty/GCC/RP2350_ARM_NTZ
$ARM_TOOLCHAIN_URL = 'https://developer.arm.com/-/media/Files/downloads/gnu/14.2.rel1/binrel/arm-gnu-toolchain-14.2.rel1-mingw-w64-i686-arm-none-eabi.zip'

$PICO_SDK_BASE     = Join-Path $env:USERPROFILE '.pico-sdk'
$SDK_DIR           = Join-Path $PICO_SDK_BASE "sdk\$SDK_VERSION"
$TOOLCHAIN_DIR     = Join-Path $PICO_SDK_BASE "toolchain\$TOOLCHAIN_VERSION"
$PICOTOOL_DIR      = Join-Path $PICO_SDK_BASE "picotool\$PICOTOOL_VERSION"
$OPENOCD_DIR       = Join-Path $PICO_SDK_BASE "openocd\$OPENOCD_VERSION"
$CMAKE_DIR         = Join-Path $PICO_SDK_BASE "cmake\$CMAKE_VERSION"
$NINJA_DIR         = Join-Path $PICO_SDK_BASE "ninja\$NINJA_VERSION"

# ---------------------------------------------------------------------------
# Utility helpers
# ---------------------------------------------------------------------------
function Write-Step   ($msg) { Write-Host "[*] $msg" -ForegroundColor Cyan }
function Write-Ok     ($msg) { Write-Host "[+] $msg" -ForegroundColor Green }
function Write-Warn2  ($msg) { Write-Host "[!] $msg" -ForegroundColor Yellow }
function Write-Fail   ($msg) { Write-Host "[X] $msg" -ForegroundColor Red }

function Test-Command($name) {
    return [bool](Get-Command $name -ErrorAction SilentlyContinue)
}

# Return the name of a Python command on PATH that is a REAL executable, not
# the Windows Store App Execution Alias stub (whose Source path lives under
# %LOCALAPPDATA%\Microsoft\WindowsApps\ and prints "Python not found" instead
# of running). Never invokes the command, only checks Get-Command.Source.
function Get-RealPythonCommand {
    foreach ($name in @('py', 'python', 'python3')) {
        $cmd = Get-Command $name -ErrorAction SilentlyContinue
        if (-not $cmd) { continue }
        if ($cmd.Source -match '\\WindowsApps\\') { continue }
        return [pscustomobject]@{ Name = $name; Path = $cmd.Source }
    }
    return $null
}

# Run a native command tolerating stderr output under strict mode.
# Returns the exit code without throwing. ($Args is a PS automatic variable, use $Arguments.)
function Invoke-Native {
    param([string]$Exe, [string[]]$Arguments)
    $prev = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        & $Exe @Arguments 2>&1 | ForEach-Object { Write-Host $_ }
        return $LASTEXITCODE
    } finally {
        $ErrorActionPreference = $prev
    }
}

function Invoke-Winget($id) {
    if (-not (Test-Command 'winget')) {
        Write-Warn2 "winget not available; skipping '$id'. Install manually if needed."
        return $false
    }
    Write-Step "winget install $id"
    & winget install --id $id --exact --accept-source-agreements --accept-package-agreements --silent
    return ($LASTEXITCODE -eq 0)
}

function Save-File($url, $dest) {
    Write-Step "Downloading $url"
    $tmpDir = Split-Path $dest -Parent
    if (-not (Test-Path $tmpDir)) { New-Item -ItemType Directory -Path $tmpDir -Force | Out-Null }
    # Use TLS 1.2 for older PowerShell 5.1
    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
    Invoke-WebRequest -Uri $url -OutFile $dest -UseBasicParsing
}

function Expand-Zip($zip, $dest) {
    Write-Step "Extracting $zip -> $dest"
    if (-not (Test-Path $dest)) { New-Item -ItemType Directory -Path $dest -Force | Out-Null }
    Expand-Archive -Path $zip -DestinationPath $dest -Force
}

function Add-UserPath($dir) {
    $current = [Environment]::GetEnvironmentVariable('Path', 'User')
    if ($null -eq $current) { $current = '' }
    $parts = $current -split ';' | Where-Object { $_ -ne '' }
    if ($parts -notcontains $dir) {
        Write-Step "Adding to User PATH: $dir"
        $new = ($parts + $dir) -join ';'
        [Environment]::SetEnvironmentVariable('Path', $new, 'User')
    }
    if (($env:Path -split ';') -notcontains $dir) {
        $env:Path = "$dir;$env:Path"
    }
}

function Set-UserEnv($name, $value) {
    Write-Step "Setting user env: $name = $value"
    [Environment]::SetEnvironmentVariable($name, $value, 'User')
    Set-Item -Path "Env:$name" -Value $value
}

# ---------------------------------------------------------------------------
# Tool installers
# ---------------------------------------------------------------------------
function Install-BaseTools {
    Write-Step 'Checking base tools (Git, Python, CMake, Ninja)...'

    $prev = $ErrorActionPreference
    $ErrorActionPreference = 'SilentlyContinue'
    try {
        if (-not (Test-Command 'git')) {
            Write-Warn2 'Git not found.'
            Invoke-Winget 'Git.Git' | Out-Null
        } else {
            $v = (& git --version 2>&1 | Out-String).Trim()
            Write-Ok "Git: $v"
        }

        # Real Python detection: never invokes python3, only checks Get-Command
        # and filters out the Windows Store App Execution Alias stub.
        $py = Get-RealPythonCommand
        if ($py) {
            Write-Ok "Python ($($py.Name)): $($py.Path)"
        } else {
            Write-Warn2 'No real Python interpreter on PATH (Windows Store alias skipped). build.py requires Python 3.'
            Invoke-Winget 'Python.Python.3.12' | Out-Null
        }

        if (-not (Test-Command 'cmake')) {
            Write-Warn2 'System CMake not on PATH (Pico SDK bundle will still be installed below).'
        } else {
            $v = ((& cmake --version 2>&1 | Out-String) -split "`n" | Select-Object -First 1).Trim()
            Write-Ok "CMake: $v"
        }

        if (-not (Test-Command 'ninja')) {
            Write-Warn2 'System Ninja not on PATH (Pico SDK bundle will still be installed below).'
        } else {
            $v = (& ninja --version 2>&1 | Out-String).Trim()
            Write-Ok "Ninja: $v"
        }
    } finally {
        $ErrorActionPreference = $prev
    }
}

function Install-CMakeBundle {
    if (Test-Path (Join-Path $CMAKE_DIR 'bin\cmake.exe')) {
        Write-Ok "CMake $CMAKE_VERSION already at $CMAKE_DIR"
        return
    }
    $ver = $CMAKE_VERSION.TrimStart('v')
    $url = "https://github.com/Kitware/CMake/releases/download/$CMAKE_VERSION/cmake-$ver-windows-x86_64.zip"
    $zip = Join-Path $env:TEMP "cmake-$ver.zip"
    $stage = Join-Path $env:TEMP "cmake-$ver-stage"
    Save-File $url $zip
    if (Test-Path $stage) { Remove-Item -Recurse -Force $stage }
    Expand-Zip $zip $stage
    $root = Get-ChildItem $stage -Directory | Select-Object -First 1
    New-Item -ItemType Directory -Force -Path $CMAKE_DIR | Out-Null
    Copy-Item -Path (Join-Path $root.FullName '*') -Destination $CMAKE_DIR -Recurse -Force
    Remove-Item -Recurse -Force $stage, $zip
    Add-UserPath (Join-Path $CMAKE_DIR 'bin')
    Write-Ok "CMake bundle installed at $CMAKE_DIR"
}

function Install-NinjaBundle {
    if (Test-Path (Join-Path $NINJA_DIR 'ninja.exe')) {
        Write-Ok "Ninja $NINJA_VERSION already at $NINJA_DIR"
        return
    }
    $url = "https://github.com/ninja-build/ninja/releases/download/$NINJA_VERSION/ninja-win.zip"
    $zip = Join-Path $env:TEMP "ninja-$NINJA_VERSION.zip"
    Save-File $url $zip
    New-Item -ItemType Directory -Force -Path $NINJA_DIR | Out-Null
    Expand-Zip $zip $NINJA_DIR
    Remove-Item -Force $zip
    Add-UserPath $NINJA_DIR
    Write-Ok "Ninja bundle installed at $NINJA_DIR"
}

function Install-ArmToolchain {
    if (Test-Path (Join-Path $TOOLCHAIN_DIR 'bin\arm-none-eabi-gcc.exe')) {
        Write-Ok "ARM toolchain $TOOLCHAIN_VERSION already at $TOOLCHAIN_DIR"
        return
    }
    $zip = Join-Path $env:TEMP "arm-gnu-toolchain-$TOOLCHAIN_VERSION.zip"
    $stage = Join-Path $env:TEMP "arm-gnu-toolchain-$TOOLCHAIN_VERSION-stage"
    Save-File $ARM_TOOLCHAIN_URL $zip
    if (Test-Path $stage) { Remove-Item -Recurse -Force $stage }
    Expand-Zip $zip $stage
    $root = Get-ChildItem $stage -Directory | Select-Object -First 1
    New-Item -ItemType Directory -Force -Path $TOOLCHAIN_DIR | Out-Null
    Copy-Item -Path (Join-Path $root.FullName '*') -Destination $TOOLCHAIN_DIR -Recurse -Force
    Remove-Item -Recurse -Force $stage, $zip
    Add-UserPath (Join-Path $TOOLCHAIN_DIR 'bin')
    Write-Ok "ARM toolchain installed at $TOOLCHAIN_DIR"
}

function Install-PicoSdk {
    if (Test-Path (Join-Path $SDK_DIR 'pico_sdk_init.cmake')) {
        Write-Ok "Pico SDK $SDK_VERSION already at $SDK_DIR"
        return
    }
    if (-not (Test-Command 'git')) { throw 'Git is required to clone the Pico SDK.' }
    New-Item -ItemType Directory -Force -Path (Split-Path $SDK_DIR -Parent) | Out-Null
    Write-Step "Cloning Pico SDK $SDK_VERSION into $SDK_DIR"
    $rc = Invoke-Native 'git' @('clone', '--depth', '1', '--branch', $SDK_VERSION, 'https://github.com/raspberrypi/pico-sdk', $SDK_DIR)
    if ($rc -ne 0) { throw "git clone pico-sdk failed (exit $rc)." }
    Push-Location $SDK_DIR
    try {
        $rc = Invoke-Native 'git' @('submodule', 'update', '--init', '--recursive', '--depth', '1')
        if ($rc -ne 0) { Write-Warn2 "Pico SDK submodule update returned $rc." }
    } finally { Pop-Location }
    Set-UserEnv 'PICO_SDK_PATH' $SDK_DIR
    Write-Ok "Pico SDK installed at $SDK_DIR"
}

function Install-PicoSdkTools {
    $picotoolExe = Join-Path $PICOTOOL_DIR 'picotool\picotool.exe'
    $openocdExe  = Join-Path $OPENOCD_DIR 'openocd.exe'
    $needPicotool = -not (Test-Path $picotoolExe)
    $needOpenocd  = -not (Test-Path $openocdExe)
    if (-not $needPicotool -and -not $needOpenocd) {
        Write-Ok "picotool + openocd already present."
        return
    }

    $url = "https://github.com/raspberrypi/pico-sdk-tools/releases/download/$PICO_SDK_TOOLS_TAG/pico-sdk-tools-$SDK_VERSION-x64-win.zip"
    $zip = Join-Path $env:TEMP "pico-sdk-tools-$SDK_VERSION.zip"
    $stage = Join-Path $env:TEMP "pico-sdk-tools-$SDK_VERSION-stage"
    try {
        Save-File $url $zip
    } catch {
        Write-Warn2 "Could not download pico-sdk-tools bundle from $url"
        Write-Warn2 "Install the Raspberry Pi Pico VS Code extension to populate picotool + openocd."
        return
    }
    if (Test-Path $stage) { Remove-Item -Recurse -Force $stage }
    Expand-Zip $zip $stage

    if ($needPicotool) {
        $srcPicotool = Get-ChildItem -Path $stage -Recurse -Filter 'picotool.exe' | Select-Object -First 1
        if ($srcPicotool) {
            New-Item -ItemType Directory -Force -Path (Join-Path $PICOTOOL_DIR 'picotool') | Out-Null
            Copy-Item $srcPicotool.FullName (Join-Path $PICOTOOL_DIR 'picotool\picotool.exe') -Force
            Add-UserPath (Join-Path $PICOTOOL_DIR 'picotool')
            Write-Ok "picotool installed at $PICOTOOL_DIR"
        } else {
            Write-Warn2 "picotool.exe not found in downloaded bundle."
        }
    }

    if ($needOpenocd) {
        $srcOpenocd = Get-ChildItem -Path $stage -Recurse -Filter 'openocd.exe' | Select-Object -First 1
        if ($srcOpenocd) {
            New-Item -ItemType Directory -Force -Path $OPENOCD_DIR | Out-Null
            Copy-Item $srcOpenocd.FullName (Join-Path $OPENOCD_DIR 'openocd.exe') -Force
            $scriptsSrc = Join-Path $srcOpenocd.Directory.FullName 'scripts'
            if (Test-Path $scriptsSrc) {
                Copy-Item -Path $scriptsSrc -Destination $OPENOCD_DIR -Recurse -Force
            }
            Write-Ok "openocd installed at $OPENOCD_DIR"
        } else {
            Write-Warn2 "openocd.exe not found in downloaded bundle."
        }
    }

    Remove-Item -Recurse -Force $stage, $zip -ErrorAction SilentlyContinue
}

function Install-AllTools {
    # Each step is guarded so PICO_SDK_PATH/PICO_TOOLCHAIN_PATH are always set at the end.
    $steps = @(
        @{ Name = 'Base tools';   Action = { Install-BaseTools } },
        @{ Name = 'CMake';        Action = { Install-CMakeBundle } },
        @{ Name = 'Ninja';        Action = { Install-NinjaBundle } },
        @{ Name = 'ARM toolchain'; Action = { Install-ArmToolchain } },
        @{ Name = 'Pico SDK';     Action = { Install-PicoSdk } },
        @{ Name = 'Pico SDK tools'; Action = { Install-PicoSdkTools } }
    )
    foreach ($s in $steps) {
        try { & $s.Action }
        catch {
            Write-Fail "$($s.Name) step failed: $_"
        }
    }
    if (Test-Path (Join-Path $SDK_DIR 'pico_sdk_init.cmake')) {
        Set-UserEnv 'PICO_SDK_PATH' $SDK_DIR
    }
    if (Test-Path (Join-Path $TOOLCHAIN_DIR 'bin')) {
        Set-UserEnv 'PICO_TOOLCHAIN_PATH' $TOOLCHAIN_DIR
    }
}

# ---------------------------------------------------------------------------
# Embedded file contents
# ---------------------------------------------------------------------------
function Get-MainC {
@'
/*
 * main.c - __PROJECT_NAME__ firmware entry point (FreeRTOS on RP2354B)
 */

#include "CONFIG.h"

#include "FreeRTOS.h"
#include "task.h"

#include "pico/stdlib.h"
#include "hardware/gpio.h"
#include "hardware/watchdog.h"
#include "hardware/clocks.h"

#define WATCHDOG_TIMEOUT_MS 2000

static void heartbeat_task(void *param)
{
    (void)param;

    gpio_init(PIN_HEARTBEAT);
    gpio_set_dir(PIN_HEARTBEAT, GPIO_OUT);

    bool led = false;
    for (;;)
    {
        led = !led;
        gpio_put(PIN_HEARTBEAT, led);
        vTaskDelay(pdMS_TO_TICKS(500));
        watchdog_update();
    }
}

void vAssertCalled(const char *file, int line)
{
    (void)file;
    (void)line;
    taskDISABLE_INTERRUPTS();
    for (;;) { tight_loop_contents(); }
}

void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    (void)xTask;
    (void)pcTaskName;
    watchdog_reboot(0, 0, 100);
    for (;;) { tight_loop_contents(); }
}

void vApplicationMallocFailedHook(void)
{
    watchdog_reboot(0, 0, 100);
    for (;;) { tight_loop_contents(); }
}

int main(void)
{
    set_sys_clock_khz(150000, true);
    watchdog_enable(WATCHDOG_TIMEOUT_MS, true);

    xTaskCreate(heartbeat_task, "hb", 256, NULL, HEARTBEAT_TASK_PRIORITY, NULL);

    vTaskStartScheduler();

    for (;;) { tight_loop_contents(); }
    return 0;
}
'@
}

function Get-ConfigH {
@'
/*
 * CONFIG.h - BladeCore-M54C Board Pin Configuration
 *
 * Pin assignments derived from the BladeCore-M54C hardware schematics (v1.0.0).
 * MCU: RP2354B (QFN-80)
 */

#ifndef CONFIG_H
#define CONFIG_H

/* -------------------------------------------------------------------------- */
/*  MCP2515 CAN Controller (SPI1)                                             */
/* -------------------------------------------------------------------------- */
#define PIN_CAN_MISO 28 /* SPI1 RX  - MCP2515 SO             */
#define PIN_CAN_CS 29   /* SPI1 CSn - MCP2515 CS (active low)*/
#define PIN_CAN_SCK 30  /* SPI1 SCK - MCP2515 SCK            */
#define PIN_CAN_MOSI 31 /* SPI1 TX  - MCP2515 SI             */

/* -------------------------------------------------------------------------- */
/*  I2C0 - Onboard EEPROM (AT24C256) + M.2 connector                         */
/* -------------------------------------------------------------------------- */
#define PIN_I2C0_SDA 32 /* I2C0 data  (4.7K pull-up)         */
#define PIN_I2C0_SCL 33 /* I2C0 clock (4.7K pull-up)         */

/* -------------------------------------------------------------------------- */
/*  MCP2515 CAN Control                                                       */
/* -------------------------------------------------------------------------- */
#define PIN_CAN_RST 34 /* MCP2515 hardware reset (active low)*/
#define PIN_CAN_INT 35 /* MCP2515 interrupt (active low)    */

/* -------------------------------------------------------------------------- */
/*  Onboard Heartbeat LED                                                     */
/* -------------------------------------------------------------------------- */
#define PIN_HEARTBEAT 36 /* Blue LED, 100R series resistor    */

/* -------------------------------------------------------------------------- */
/*  ADC - Onboard                                                             */
/* -------------------------------------------------------------------------- */
#define PIN_ADC_VUSB 46 /* GPIO46/ADC6 - USB VBUS sense (5.1K-5.1K divider) */
#define PIN_ADC_VREF 47 /* GPIO47/ADC7 - 3.00V 0.1% ref (10K-10K divider)   */

/* -------------------------------------------------------------------------- */
/*  Unused GPIOs - M.2 Connector (directly access through M.2 edge connector) */
/* -------------------------------------------------------------------------- */
/*  Left side (odd pins)                                                      */
// #define PIN_GPIO0             0       /* M.2 pin 57             */
// #define PIN_GPIO1             1       /* M.2 pin 55             */
// #define PIN_GPIO2             2       /* M.2 pin 53             */
// #define PIN_GPIO3             3       /* M.2 pin 51             */
// #define PIN_GPIO4             4       /* M.2 pin 49             */
// #define PIN_GPIO5             5       /* M.2 pin 47             */
// #define PIN_GPIO6             6       /* M.2 pin 45             */
// #define PIN_GPIO7             7       /* M.2 pin 43             */
// #define PIN_GPIO8             8       /* M.2 pin 39             */
// #define PIN_GPIO9             9       /* M.2 pin 37             */
// #define PIN_GPIO10            10      /* M.2 pin 35             */
// #define PIN_GPIO11            11      /* M.2 pin 33             */
// #define PIN_GPIO12            12      /* M.2 pin 31             */
// #define PIN_GPIO13            13      /* M.2 pin 29             */
// #define PIN_GPIO14            14      /* M.2 pin 27             */
// #define PIN_GPIO15            15      /* M.2 pin 25             */
// #define PIN_GPIO16            16      /* M.2 pin 21             */
// #define PIN_GPIO17            17      /* M.2 pin 19             */
// #define PIN_GPIO18            18      /* M.2 pin 17             */
// #define PIN_GPIO19            19      /* M.2 pin 15             */
// #define PIN_GPIO20            20      /* M.2 pin 13             */
// #define PIN_GPIO21            21      /* M.2 pin 9              */
// #define PIN_GPIO22            22      /* M.2 pin 7              */
// #define PIN_GPIO23            23      /* M.2 pin 5              */
// #define PIN_GPIO24            24      /* M.2 pin 3              */
/*  Right side (even pins)                                                    */
// #define PIN_GPIO25            25      /* M.2 pin 8              */
// #define PIN_GPIO26            26      /* M.2 pin 6              */
// #define PIN_GPIO27            27      /* M.2 pin 4              */
// #define PIN_GPIO37            37      /* M.2 pin 34             */
// #define PIN_GPIO38            38      /* M.2 pin 36             */
// #define PIN_GPIO39            39      /* M.2 pin 40             */
// #define PIN_ADC0              40      /* M.2 pin 46 / ADC0      */
// #define PIN_ADC1              41      /* M.2 pin 48 / ADC1      */
// #define PIN_ADC2              42      /* M.2 pin 50 / ADC2      */
// #define PIN_ADC3              43      /* M.2 pin 52 / ADC3      */
// #define PIN_ADC4              44      /* M.2 pin 54 / ADC4      */
// #define PIN_ADC5              45      /* M.2 pin 56 / ADC5      */
/*  CAN bus signals (directly from TCAN1044, no GPIO)                         */
// CAN_P                                /* M.2 pin 28             */
// CAN_N                                /* M.2 pin 30             */

/* -------------------------------------------------------------------------- */
/*  SPI1 instance used by MCP2515                                             */
/* -------------------------------------------------------------------------- */
#define CAN_SPI_INSTANCE spi1
#define CAN_SPI_BAUDRATE (10 * 1000 * 1000) /* 10 MHz               */

/* -------------------------------------------------------------------------- */
/*  I2C0 instance used by EEPROM                                              */
/* -------------------------------------------------------------------------- */
#define EEPROM_I2C_INSTANCE i2c0
#define EEPROM_I2C_ADDR 0x50             /* AT24C256 base address (A0=A1=GND) */
#define EEPROM_I2C_BAUDRATE (400 * 1000) /* 400 kHz             */

/* -------------------------------------------------------------------------- */
/*  Heartbeat LED - PWM configuration                                         */
/* -------------------------------------------------------------------------- */
/*  GPIO36 -> PWM slice 2, channel A (RP2354B: slice = (gpio >> 1) & 0xF)    */
#define HEARTBEAT_PWM_FREQ_HZ 1000
#define HEARTBEAT_FADE_STEP_MS 8

#endif /* CONFIG_H */
'@
}

function Get-FreeRTOSConfigH {
@'
/*
 * FreeRTOSConfig.h - FreeRTOS configuration for RP2354B (Cortex-M33)
 */

#ifndef FREERTOS_CONFIG_H
#define FREERTOS_CONFIG_H

/* ISR handlers -- use Pico SDK ISR names */
#define vPortSVCHandler     isr_svcall
#define xPortPendSVHandler  isr_pendsv
#define xPortSysTickHandler isr_systick

/* -------------------------------------------------------------------------- */
/*  Task priorities                                                           */
/* -------------------------------------------------------------------------- */
#define HEARTBEAT_TASK_PRIORITY (tskIDLE_PRIORITY + 1)

/* -------------------------------------------------------------------------- */
/*  Scheduler                                                                 */
/* -------------------------------------------------------------------------- */
#define configUSE_PREEMPTION                    1
#define configUSE_TIME_SLICING                  1
#define configUSE_PORT_OPTIMISED_TASK_SELECTION 0
#define configUSE_TICKLESS_IDLE                 0
#define configCPU_CLOCK_HZ                      150000000UL
#define configTICK_RATE_HZ                      ((TickType_t)1000)
#define configMAX_PRIORITIES                    16
#define configMINIMAL_STACK_SIZE                ((configSTACK_DEPTH_TYPE)256)
#define configUSE_16_BIT_TICKS                  0
#define configIDLE_SHOULD_YIELD                 1
#define configMAX_TASK_NAME_LEN                 16
#define configTASK_NOTIFICATION_ARRAY_ENTRIES   3

/* -------------------------------------------------------------------------- */
/*  Synchronization                                                           */
/* -------------------------------------------------------------------------- */
#define configUSE_MUTEXES                       1
#define configUSE_RECURSIVE_MUTEXES             0
#define configUSE_COUNTING_SEMAPHORES           1
#define configUSE_TASK_NOTIFICATIONS            1
#define configUSE_QUEUE_SETS                    0
#define configQUEUE_REGISTRY_SIZE               8
#define configUSE_NEWLIB_REENTRANT              0
#define configENABLE_BACKWARD_COMPATIBILITY     0
#define configNUM_THREAD_LOCAL_STORAGE_POINTERS 5

/* -------------------------------------------------------------------------- */
/*  System types                                                              */
/* -------------------------------------------------------------------------- */
#define configSTACK_DEPTH_TYPE                  uint32_t
#define configMESSAGE_BUFFER_LENGTH_TYPE        size_t

/* -------------------------------------------------------------------------- */
/*  Memory allocation                                                         */
/* -------------------------------------------------------------------------- */
#define configSUPPORT_STATIC_ALLOCATION         0
#define configSUPPORT_DYNAMIC_ALLOCATION        1
#define configAPPLICATION_ALLOCATED_HEAP        0
#define configTOTAL_HEAP_SIZE                   (64 * 1024)

/* -------------------------------------------------------------------------- */
/*  Hooks                                                                     */
/* -------------------------------------------------------------------------- */
#define configUSE_IDLE_HOOK                     0
#define configUSE_TICK_HOOK                     0
#define configCHECK_FOR_STACK_OVERFLOW          2
#define configUSE_MALLOC_FAILED_HOOK            1
#define configUSE_DAEMON_TASK_STARTUP_HOOK      0

/* -------------------------------------------------------------------------- */
/*  Runtime stats / trace                                                     */
/* -------------------------------------------------------------------------- */
#define configGENERATE_RUN_TIME_STATS           0
#define configUSE_TRACE_FACILITY                0
#define configUSE_STATS_FORMATTING_FUNCTIONS    0

/* -------------------------------------------------------------------------- */
/*  Co-routines (disabled)                                                    */
/* -------------------------------------------------------------------------- */
#define configUSE_CO_ROUTINES                   0
#define configMAX_CO_ROUTINE_PRIORITIES         1

/* -------------------------------------------------------------------------- */
/*  Software timers                                                           */
/* -------------------------------------------------------------------------- */
#define configUSE_TIMERS                        1
#define configTIMER_TASK_PRIORITY               (tskIDLE_PRIORITY + 2)
#define configTIMER_QUEUE_LENGTH                10
#define configTIMER_TASK_STACK_DEPTH            512

/* -------------------------------------------------------------------------- */
/*  Cortex-M33 (RP2350/RP2354) required defines                               */
/* -------------------------------------------------------------------------- */
#define configENABLE_FPU                        1
#define configENABLE_MPU                        0
#define configENABLE_TRUSTZONE                  0
#define configRUN_FREERTOS_SECURE_ONLY          1
#define configNUMBER_OF_CORES                   1

#define configPRIO_BITS                         4
#define configMAX_SYSCALL_INTERRUPT_PRIORITY    16

/* -------------------------------------------------------------------------- */
/*  RP2350 / Pico SDK interop                                                 */
/* -------------------------------------------------------------------------- */
#define configSUPPORT_PICO_SYNC_INTEROP         1
#define configSUPPORT_PICO_TIME_INTEROP         1

/* -------------------------------------------------------------------------- */
/*  Assert                                                                    */
/* -------------------------------------------------------------------------- */
void vAssertCalled(const char *file, int line);
#define configASSERT(x)                    \
    if ((x) == 0)                          \
    {                                      \
        vAssertCalled(__FILE__, __LINE__); \
    }

/* -------------------------------------------------------------------------- */
/*  Optional API includes                                                     */
/* -------------------------------------------------------------------------- */
#define INCLUDE_vTaskPrioritySet             1
#define INCLUDE_uxTaskPriorityGet            1
#define INCLUDE_vTaskDelete                  1
#define INCLUDE_vTaskSuspend                 1
#define INCLUDE_vTaskDelayUntil              1
#define INCLUDE_vTaskDelay                   1
#define INCLUDE_xTimerPendFunctionCall       1
#define INCLUDE_xTaskGetSchedulerState       1
#define INCLUDE_xTaskGetCurrentTaskHandle    1
#define INCLUDE_uxTaskGetStackHighWaterMark  1
#define INCLUDE_uxTaskGetStackHighWaterMark2 1
#define INCLUDE_xTaskGetIdleTaskHandle       1
#define INCLUDE_eTaskGetState                1
#define INCLUDE_xTaskAbortDelay              1
#define INCLUDE_xTaskGetHandle               1
#define INCLUDE_xTaskResumeFromISR           1
#define INCLUDE_xQueueGetMutexHolder         1
#define INCLUDE_xResumeFromISR               1

#endif /* FREERTOS_CONFIG_H */
'@
}

function Get-CMakeLists {
@'
cmake_minimum_required(VERSION 3.13)

set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# == DO NOT EDIT THE FOLLOWING LINES for the Raspberry Pi Pico VS Code Extension to work ==
if(WIN32)
    set(USERHOME $ENV{USERPROFILE})
else()
    set(USERHOME $ENV{HOME})
endif()
set(sdkVersion 2.2.0)
set(toolchainVersion 14_2_Rel1)
set(picotoolVersion 2.2.0-a4)
set(picoVscode ${USERHOME}/.pico-sdk/cmake/pico-vscode.cmake)
if (EXISTS ${picoVscode})
    include(${picoVscode})
endif()
# ====================================================================================
set(PICO_BOARD pico2 CACHE STRING "Board type")

# FreeRTOS kernel path
set(FREERTOS_KERNEL_PATH ${CMAKE_CURRENT_LIST_DIR}/FreeRTOS-Kernel)
set(FREERTOS_CONFIG_FILE_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})

# Pull in Raspberry Pi Pico SDK (must be before project)
include(pico_sdk_import.cmake)

# Pull in FreeRTOS RP2350 Cortex-M33 NTZ port
include(${FREERTOS_KERNEL_PATH}/portable/ThirdParty/GCC/RP2350_ARM_NTZ/FreeRTOS_Kernel_import.cmake)

project(__PROJECT_NAME__ C CXX ASM)

# Initialise the Raspberry Pi Pico SDK
pico_sdk_init()

add_executable(__PROJECT_NAME__
    main.c
    # === USER SOURCES BEGIN === (managed by Create_M54C_RTOS.ps1 -Update)
    # === USER SOURCES END ===
)

pico_set_program_name(__PROJECT_NAME__ "__PROJECT_NAME__")
pico_set_program_version(__PROJECT_NAME__ "0.1.0")

pico_enable_stdio_uart(__PROJECT_NAME__ 0)
pico_enable_stdio_usb(__PROJECT_NAME__ 0)

target_include_directories(__PROJECT_NAME__ PRIVATE
    ${CMAKE_CURRENT_LIST_DIR}
    ${CMAKE_CURRENT_LIST_DIR}/incl
    # === USER INCLUDE DIRS BEGIN === (managed by Create_M54C_RTOS.ps1 -Update)
    # === USER INCLUDE DIRS END ===
)

target_link_libraries(__PROJECT_NAME__
    pico_stdlib
    hardware_gpio
    hardware_watchdog
    hardware_clocks
    hardware_timer
    FreeRTOS-Kernel-Heap4
)

pico_add_extra_outputs(__PROJECT_NAME__)
'@
}

function Get-PicoSdkImport {
@'
# This is a copy of <PICO_SDK_PATH>/external/pico_sdk_import.cmake

# This can be dropped into an external project to help locate this SDK
# It should be include()ed prior to project()

if (DEFINED ENV{PICO_SDK_PATH} AND (NOT PICO_SDK_PATH))
    set(PICO_SDK_PATH $ENV{PICO_SDK_PATH})
    message("Using PICO_SDK_PATH from environment ('${PICO_SDK_PATH}')")
endif ()

if (DEFINED ENV{PICO_SDK_FETCH_FROM_GIT} AND (NOT PICO_SDK_FETCH_FROM_GIT))
    set(PICO_SDK_FETCH_FROM_GIT $ENV{PICO_SDK_FETCH_FROM_GIT})
    message("Using PICO_SDK_FETCH_FROM_GIT from environment ('${PICO_SDK_FETCH_FROM_GIT}')")
endif ()

if (DEFINED ENV{PICO_SDK_FETCH_FROM_GIT_PATH} AND (NOT PICO_SDK_FETCH_FROM_GIT_PATH))
    set(PICO_SDK_FETCH_FROM_GIT_PATH $ENV{PICO_SDK_FETCH_FROM_GIT_PATH})
    message("Using PICO_SDK_FETCH_FROM_GIT_PATH from environment ('${PICO_SDK_FETCH_FROM_GIT_PATH}')")
endif ()

if (DEFINED ENV{PICO_SDK_FETCH_FROM_GIT_TAG} AND (NOT PICO_SDK_FETCH_FROM_GIT_TAG))
    set(PICO_SDK_FETCH_FROM_GIT_TAG $ENV{PICO_SDK_FETCH_FROM_GIT_TAG})
    message("Using PICO_SDK_FETCH_FROM_GIT_TAG from environment ('${PICO_SDK_FETCH_FROM_GIT_TAG}')")
endif ()

if (PICO_SDK_FETCH_FROM_GIT AND NOT PICO_SDK_FETCH_FROM_GIT_TAG)
  set(PICO_SDK_FETCH_FROM_GIT_TAG "master")
  message("Using master as default value for PICO_SDK_FETCH_FROM_GIT_TAG")
endif()

set(PICO_SDK_PATH "${PICO_SDK_PATH}" CACHE PATH "Path to the Raspberry Pi Pico SDK")
set(PICO_SDK_FETCH_FROM_GIT "${PICO_SDK_FETCH_FROM_GIT}" CACHE BOOL "Set to ON to fetch copy of SDK from git if not otherwise locatable")
set(PICO_SDK_FETCH_FROM_GIT_PATH "${PICO_SDK_FETCH_FROM_GIT_PATH}" CACHE FILEPATH "location to download SDK")
set(PICO_SDK_FETCH_FROM_GIT_TAG "${PICO_SDK_FETCH_FROM_GIT_TAG}" CACHE FILEPATH "release tag for SDK")

if (NOT PICO_SDK_PATH)
    if (PICO_SDK_FETCH_FROM_GIT)
        include(FetchContent)
        set(FETCHCONTENT_BASE_DIR_SAVE ${FETCHCONTENT_BASE_DIR})
        if (PICO_SDK_FETCH_FROM_GIT_PATH)
            get_filename_component(FETCHCONTENT_BASE_DIR "${PICO_SDK_FETCH_FROM_GIT_PATH}" REALPATH BASE_DIR "${CMAKE_SOURCE_DIR}")
        endif ()
        FetchContent_Declare(
                pico_sdk
                GIT_REPOSITORY https://github.com/raspberrypi/pico-sdk
                GIT_TAG ${PICO_SDK_FETCH_FROM_GIT_TAG}
        )

        if (NOT pico_sdk)
            message("Downloading Raspberry Pi Pico SDK")
            if (${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.17.0")
                FetchContent_Populate(
                        pico_sdk
                        QUIET
                        GIT_REPOSITORY https://github.com/raspberrypi/pico-sdk
                        GIT_TAG ${PICO_SDK_FETCH_FROM_GIT_TAG}
                        GIT_SUBMODULES_RECURSE FALSE

                        SOURCE_DIR ${FETCHCONTENT_BASE_DIR}/pico_sdk-src
                        BINARY_DIR ${FETCHCONTENT_BASE_DIR}/pico_sdk-build
                        SUBBUILD_DIR ${FETCHCONTENT_BASE_DIR}/pico_sdk-subbuild
                )
            else ()
                FetchContent_Populate(
                        pico_sdk
                        QUIET
                        GIT_REPOSITORY https://github.com/raspberrypi/pico-sdk
                        GIT_TAG ${PICO_SDK_FETCH_FROM_GIT_TAG}

                        SOURCE_DIR ${FETCHCONTENT_BASE_DIR}/pico_sdk-src
                        BINARY_DIR ${FETCHCONTENT_BASE_DIR}/pico_sdk-build
                        SUBBUILD_DIR ${FETCHCONTENT_BASE_DIR}/pico_sdk-subbuild
                )
            endif ()

            set(PICO_SDK_PATH ${pico_sdk_SOURCE_DIR})
        endif ()
        set(FETCHCONTENT_BASE_DIR ${FETCHCONTENT_BASE_DIR_SAVE})
    else ()
        message(FATAL_ERROR
                "SDK location was not specified. Please set PICO_SDK_PATH or set PICO_SDK_FETCH_FROM_GIT to on to fetch from git."
                )
    endif ()
endif ()

get_filename_component(PICO_SDK_PATH "${PICO_SDK_PATH}" REALPATH BASE_DIR "${CMAKE_BINARY_DIR}")
if (NOT EXISTS ${PICO_SDK_PATH})
    message(FATAL_ERROR "Directory '${PICO_SDK_PATH}' not found")
endif ()

set(PICO_SDK_INIT_CMAKE_FILE ${PICO_SDK_PATH}/pico_sdk_init.cmake)
if (NOT EXISTS ${PICO_SDK_INIT_CMAKE_FILE})
    message(FATAL_ERROR "Directory '${PICO_SDK_PATH}' does not appear to contain the Raspberry Pi Pico SDK")
endif ()

set(PICO_SDK_PATH ${PICO_SDK_PATH} CACHE PATH "Path to the Raspberry Pi Pico SDK" FORCE)

include(${PICO_SDK_INIT_CMAKE_FILE})
'@
}

function Get-BuildPy {
@'
#!/usr/bin/env python3
"""
__PROJECT_NAME__ Firmware Build and Upload Script
=================================================
Universal script, works on any PC regardless of installation paths.
Requires Python 3. Invoke as `python build.py` or `python3 build.py`.

Usage:
    python build.py              # configure if needed, then build
    python build.py clean        # delete build directory
    python build.py rebuild      # clean, configure, build
    python build.py upload       # build, then flash via picotool (BOOTSEL)
    python build.py size         # show memory usage of last build
"""
import os
import sys
import glob
import shutil
import subprocess
import platform

PROJECT_NAME = "__PROJECT_NAME__"

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BUILD_DIR  = os.path.join(SCRIPT_DIR, "build")
UF2_FILE   = os.path.join(BUILD_DIR, PROJECT_NAME + ".uf2")
ELF_FILE   = os.path.join(BUILD_DIR, PROJECT_NAME + ".elf")

if platform.system() == "Windows":
    _USER_HOME = os.environ.get("USERPROFILE", "")
else:
    _USER_HOME = os.environ.get("HOME", "")

_PICO_SDK_BASE = os.path.join(_USER_HOME, ".pico-sdk")


def _find_tool(name, *fallback_paths):
    found = shutil.which(name)
    if found:
        return found
    for p in fallback_paths:
        if os.path.isfile(p):
            return p
    return None


def _newest_glob(pattern):
    matches = sorted(glob.glob(pattern))
    return matches[-1] if matches else None


def find_cmake():
    tool = _find_tool(
        "cmake",
        os.path.join(_PICO_SDK_BASE, "cmake", "v3.31.5", "bin", "cmake.exe"),
        r"C:\Program Files\CMake\bin\cmake.exe",
        r"C:\Program Files (x86)\CMake\bin\cmake.exe",
    )
    if not tool:
        tool = _newest_glob(os.path.join(_PICO_SDK_BASE, "cmake", "*", "bin", "cmake*"))
    if not tool:
        sys.exit("[ERROR] cmake not found.")
    return tool


def find_ninja():
    tool = _find_tool(
        "ninja",
        os.path.join(_PICO_SDK_BASE, "ninja", "v1.12.1", "ninja.exe"),
    )
    if not tool:
        tool = _newest_glob(os.path.join(_PICO_SDK_BASE, "ninja", "*", "ninja*"))
    if not tool:
        sys.exit("[ERROR] ninja not found.")
    return tool


def find_picotool():
    tool = _find_tool("picotool")
    if tool:
        return tool
    ext = ".exe" if platform.system() == "Windows" else ""
    tool = _newest_glob(os.path.join(_PICO_SDK_BASE, "picotool", "*", "picotool", "picotool" + ext))
    if tool:
        return tool
    sys.exit("[ERROR] picotool not found.")


def _find_toolchain_bin():
    return _newest_glob(os.path.join(_PICO_SDK_BASE, "toolchain", "*", "bin"))


def find_size():
    tool = _find_tool("arm-none-eabi-size")
    if tool:
        return tool
    tc_bin = _find_toolchain_bin()
    if tc_bin:
        for name in ("arm-none-eabi-size.exe", "arm-none-eabi-size"):
            p = os.path.join(tc_bin, name)
            if os.path.isfile(p):
                return p
    return None


def find_pico_sdk():
    env = os.environ.get("PICO_SDK_PATH", "")
    if env and os.path.isdir(env):
        return env
    found = _newest_glob(os.path.join(_PICO_SDK_BASE, "sdk", "*"))
    if found and os.path.isdir(found):
        return found
    sys.exit("[ERROR] Pico SDK not found. Set PICO_SDK_PATH.")


def find_pico_toolchain():
    env = os.environ.get("PICO_TOOLCHAIN_PATH", "")
    if env and os.path.isdir(env):
        return env
    found = _newest_glob(os.path.join(_PICO_SDK_BASE, "toolchain", "*"))
    if found and os.path.isdir(found):
        return found
    return None


def _run(cmd, env=None):
    print(f"[RUN] {' '.join(str(c) for c in cmd)}")
    result = subprocess.run(cmd, env=env)
    if result.returncode != 0:
        sys.exit(f"[ERROR] Command failed with exit code {result.returncode}")


def do_clean():
    if os.path.isdir(BUILD_DIR):
        print(f"[*] Removing {BUILD_DIR}")
        shutil.rmtree(BUILD_DIR)
    else:
        print("[*] Build directory does not exist.")


def do_configure():
    cmake = find_cmake()
    ninja = find_ninja()
    sdk   = find_pico_sdk()
    tc    = find_pico_toolchain()

    os.makedirs(BUILD_DIR, exist_ok=True)

    env = os.environ.copy()
    env["PICO_SDK_PATH"] = sdk
    if tc:
        env["PICO_TOOLCHAIN_PATH"] = tc
        tc_bin = os.path.join(tc, "bin")
        if tc_bin not in env.get("PATH", ""):
            env["PATH"] = tc_bin + os.pathsep + env.get("PATH", "")

    cmd = [
        cmake,
        "-G", "Ninja",
        f"-DCMAKE_MAKE_PROGRAM={ninja}",
        f"-DPICO_SDK_PATH={sdk}",
        "-B", BUILD_DIR,
        "-S", SCRIPT_DIR,
    ]
    print("[*] Configuring CMake...")
    _run(cmd, env=env)


def do_build():
    cmake = find_cmake()
    if not os.path.isfile(os.path.join(BUILD_DIR, "CMakeCache.txt")):
        do_configure()
    print("[*] Building firmware...")
    _run([cmake, "--build", BUILD_DIR, "--", "-j4"])
    print("\n[+] BUILD SUCCESSFUL")
    do_size()


def do_size():
    size = find_size()
    if size and os.path.isfile(ELF_FILE):
        print("\n=== Memory Usage ===")
        subprocess.run([size, ELF_FILE])
        print("\n=== Output Files ===")
        for f in (UF2_FILE, ELF_FILE):
            if os.path.isfile(f):
                print(f"   {os.path.basename(f)}  -  {os.path.getsize(f):,} bytes")
    elif not os.path.isfile(ELF_FILE):
        print("[!] No ELF found. Run build first.")


def do_upload():
    if not os.path.isfile(UF2_FILE):
        print("[*] UF2 not found, building first.")
        do_build()

    picotool = find_picotool()
    print("\n[*] Flashing via picotool (put board in BOOTSEL mode)...")
    _run([picotool, "load", UF2_FILE, "-f"])
    print("[*] Rebooting board...")
    _run([picotool, "reboot"])
    print("\n[+] FLASH SUCCESSFUL")


def main():
    action = sys.argv[1].lower() if len(sys.argv) > 1 else "build"
    if action == "clean":
        do_clean()
    elif action == "configure":
        do_configure()
    elif action == "rebuild":
        do_clean()
        do_build()
    elif action == "upload":
        do_upload()
    elif action == "size":
        do_size()
    elif action == "build":
        do_build()
    else:
        print(__doc__)
        sys.exit(f"[ERROR] Unknown action: {action}")


if __name__ == "__main__":
    main()
'@
}

function Get-GitIgnore {
@'
build/
.vs/
*.uf2
*.elf
*.bin
*.hex
*.dis
*.map
__pycache__/
*.pyc
'@
}

function Get-VscodeCmakeKits {
@'
[
    {
        "name": "Pico",
        "compilers": {
            "C": "${command:raspberry-pi-pico.getCompilerPath}",
            "CXX": "${command:raspberry-pi-pico.getCxxCompilerPath}"
        },
        "environmentVariables": {
            "PATH": "${command:raspberry-pi-pico.getEnvPath};${env:PATH}"
        },
        "cmakeSettings": {
            "Python3_EXECUTABLE": "${command:raspberry-pi-pico.getPythonPath}"
        }
    }
]
'@
}

function Get-VscodeCppProperties {
@'
{
    "configurations": [
        {
            "name": "Pico",
            "includePath": [
                "${workspaceFolder}/**",
                "${userHome}/.pico-sdk/sdk/2.2.0/**"
            ],
            "forcedInclude": [
                "${workspaceFolder}/build/generated/pico_base/pico/config_autogen.h",
                "${userHome}/.pico-sdk/sdk/2.2.0/src/common/pico_base_headers/include/pico.h"
            ],
            "defines": [],
            "compilerPath": "${userHome}/.pico-sdk/toolchain/14_2_Rel1/bin/arm-none-eabi-gcc.exe",
            "compileCommands": "${workspaceFolder}/build/compile_commands.json",
            "cStandard": "c17",
            "cppStandard": "c++14",
            "intelliSenseMode": "linux-gcc-arm"
        }
    ],
    "version": 4
}
'@
}

function Get-VscodeExtensions {
@'
{
    "recommendations": [
        "marus25.cortex-debug",
        "ms-vscode.cpptools",
        "ms-vscode.cpptools-extension-pack",
        "ms-vscode.vscode-serial-monitor",
        "raspberry-pi.raspberry-pi-pico"
    ]
}
'@
}

function Get-VscodeLaunch {
@'
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Pico Debug (Cortex-Debug)",
            "cwd": "${userHome}/.pico-sdk/openocd/0.12.0+dev/scripts",
            "executable": "${command:raspberry-pi-pico.launchTargetPath}",
            "request": "launch",
            "type": "cortex-debug",
            "servertype": "openocd",
            "serverpath": "${userHome}/.pico-sdk/openocd/0.12.0+dev/openocd.exe",
            "gdbPath": "${command:raspberry-pi-pico.getGDBPath}",
            "debuggerArgs": ["-ex", "set debug-file-directory /debug"],
            "device": "${command:raspberry-pi-pico.getChipUppercase}",
            "configFiles": [
                "interface/cmsis-dap.cfg",
                "target/${command:raspberry-pi-pico.getTarget}.cfg"
            ],
            "svdFile": "${userHome}/.pico-sdk/sdk/2.2.0/src/${command:raspberry-pi-pico.getChip}/hardware_regs/${command:raspberry-pi-pico.getChipUppercase}.svd",
            "runToEntryPoint": "main",
            "overrideLaunchCommands": [
                "monitor reset init",
                "load \"${command:raspberry-pi-pico.launchTargetPath}\""
            ],
            "openOCDLaunchCommands": [
                "adapter speed 5000"
            ]
        },
        {
            "name": "Pico Debug (Cortex-Debug with external OpenOCD)",
            "cwd": "${workspaceRoot}",
            "executable": "${command:raspberry-pi-pico.launchTargetPath}",
            "request": "launch",
            "type": "cortex-debug",
            "servertype": "external",
            "gdbTarget": "localhost:3333",
            "gdbPath": "${command:raspberry-pi-pico.getGDBPath}",
            "debuggerArgs": ["-ex", "set debug-file-directory /debug"],
            "device": "${command:raspberry-pi-pico.getChipUppercase}",
            "svdFile": "${userHome}/.pico-sdk/sdk/2.2.0/src/${command:raspberry-pi-pico.getChip}/hardware_regs/${command:raspberry-pi-pico.getChipUppercase}.svd",
            "runToEntryPoint": "main",
            "overrideLaunchCommands": [
                "monitor reset init",
                "load \"${command:raspberry-pi-pico.launchTargetPath}\""
            ]
        }
    ]
}
'@
}

function Get-VscodeSettings {
@'
{
    "cmake.showSystemKits": false,
    "cmake.options.statusBarVisibility": "hidden",
    "cmake.options.advanced": {
        "build": { "statusBarVisibility": "hidden" },
        "launch": { "statusBarVisibility": "hidden" },
        "debug": { "statusBarVisibility": "hidden" },
        "variant": { "statusBarVisibility": "compact" },
        "buildTarget": { "statusBarVisibility": "visible" }
    },
    "cmake.configureOnEdit": true,
    "cmake.automaticReconfigure": true,
    "cmake.configureOnOpen": false,
    "cmake.generator": "Ninja",
    "cmake.cmakePath": "${userHome}/.pico-sdk/cmake/v3.31.5/bin/cmake",
    "C_Cpp.debugShortcut": false,
    "terminal.integrated.env.windows": {
        "PICO_SDK_PATH": "${env:USERPROFILE}/.pico-sdk/sdk/2.2.0",
        "PICO_TOOLCHAIN_PATH": "${env:USERPROFILE}/.pico-sdk/toolchain/14_2_Rel1",
        "Path": "${env:USERPROFILE}/.pico-sdk/toolchain/14_2_Rel1/bin;${env:USERPROFILE}/.pico-sdk/picotool/2.2.0-a4/picotool;${env:USERPROFILE}/.pico-sdk/cmake/v3.31.5/bin;${env:USERPROFILE}/.pico-sdk/ninja/v1.12.1;${env:PATH}"
    },
    "terminal.integrated.env.osx": {
        "PICO_SDK_PATH": "${env:HOME}/.pico-sdk/sdk/2.2.0",
        "PICO_TOOLCHAIN_PATH": "${env:HOME}/.pico-sdk/toolchain/14_2_Rel1",
        "PATH": "${env:HOME}/.pico-sdk/toolchain/14_2_Rel1/bin:${env:HOME}/.pico-sdk/picotool/2.2.0-a4/picotool:${env:HOME}/.pico-sdk/cmake/v3.31.5/bin:${env:HOME}/.pico-sdk/ninja/v1.12.1:${env:PATH}"
    },
    "terminal.integrated.env.linux": {
        "PICO_SDK_PATH": "${env:HOME}/.pico-sdk/sdk/2.2.0",
        "PICO_TOOLCHAIN_PATH": "${env:HOME}/.pico-sdk/toolchain/14_2_Rel1",
        "PATH": "${env:HOME}/.pico-sdk/toolchain/14_2_Rel1/bin:${env:HOME}/.pico-sdk/picotool/2.2.0-a4/picotool:${env:HOME}/.pico-sdk/cmake/v3.31.5/bin:${env:HOME}/.pico-sdk/ninja/v1.12.1:${env:PATH}"
    },
    "raspberry-pi-pico.cmakeAutoConfigure": false,
    "raspberry-pi-pico.useCmakeTools": true,
    "raspberry-pi-pico.cmakePath": "${HOME}/.pico-sdk/cmake/v3.31.5/bin/cmake",
    "raspberry-pi-pico.ninjaPath": "${HOME}/.pico-sdk/ninja/v1.12.1/ninja"
}
'@
}

function Get-VscodeTasks {
@'
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Compile Project",
            "type": "process",
            "isBuildCommand": true,
            "command": "${userHome}/.pico-sdk/ninja/v1.12.1/ninja",
            "args": ["-C", "${workspaceFolder}/build"],
            "group": "build",
            "presentation": { "reveal": "always", "panel": "dedicated" },
            "problemMatcher": "$gcc",
            "windows": {
                "command": "${env:USERPROFILE}/.pico-sdk/ninja/v1.12.1/ninja.exe"
            }
        },
        {
            "label": "Run Project",
            "type": "process",
            "command": "${env:HOME}/.pico-sdk/picotool/2.2.0-a4/picotool/picotool",
            "args": [
                "load",
                "${command:raspberry-pi-pico.launchTargetPath}",
                "-fx"
            ],
            "presentation": { "reveal": "always", "panel": "dedicated" },
            "problemMatcher": [],
            "windows": {
                "command": "${env:USERPROFILE}/.pico-sdk/picotool/2.2.0-a4/picotool/picotool.exe"
            }
        },
        {
            "label": "Flash",
            "type": "process",
            "command": "${userHome}/.pico-sdk/openocd/0.12.0+dev/openocd.exe",
            "args": [
                "-s",
                "${userHome}/.pico-sdk/openocd/0.12.0+dev/scripts",
                "-f",
                "interface/cmsis-dap.cfg",
                "-f",
                "target/${command:raspberry-pi-pico.getTarget}.cfg",
                "-c",
                "adapter speed 5000; program \"${command:raspberry-pi-pico.launchTargetPath}\" verify reset exit"
            ],
            "problemMatcher": [],
            "windows": {
                "command": "${env:USERPROFILE}/.pico-sdk/openocd/0.12.0+dev/openocd.exe"
            }
        },
        {
            "label": "Rescue Reset",
            "type": "process",
            "command": "${userHome}/.pico-sdk/openocd/0.12.0+dev/openocd.exe",
            "args": [
                "-s",
                "${userHome}/.pico-sdk/openocd/0.12.0+dev/scripts",
                "-f",
                "interface/cmsis-dap.cfg",
                "-f",
                "target/${command:raspberry-pi-pico.getChip}-rescue.cfg",
                "-c",
                "adapter speed 5000; reset halt; exit"
            ],
            "problemMatcher": [],
            "windows": {
                "command": "${env:USERPROFILE}/.pico-sdk/openocd/0.12.0+dev/openocd.exe"
            }
        },
        {
            "label": "RISC-V Reset (RP2350)",
            "type": "process",
            "command": "${userHome}/.pico-sdk/openocd/0.12.0+dev/openocd.exe",
            "args": [
                "-s",
                "${userHome}/.pico-sdk/openocd/0.12.0+dev/scripts",
                "-c",
                "set USE_CORE { rv0 rv1 cm0 cm1 }",
                "-f",
                "interface/cmsis-dap.cfg",
                "-f",
                "target/rp2350.cfg",
                "-c",
                "adapter speed 5000; init;",
                "-c",
                "write_memory 0x40120158 8 { 0x3 }; echo [format \"Info : ARCHSEL 0x%02x\" [read_memory 0x40120158 8 1]];",
                "-c",
                "reset halt; targets rp2350.rv0; echo [format \"Info : ARCHSEL_STATUS 0x%02x\" [read_memory 0x4012015C 8 1]]; exit"
            ],
            "problemMatcher": [],
            "windows": {
                "command": "${env:USERPROFILE}/.pico-sdk/openocd/0.12.0+dev/openocd.exe"
            }
        }
    ]
}
'@
}

# ---------------------------------------------------------------------------
# File writer
# ---------------------------------------------------------------------------
function Write-ProjectFile {
    param(
        [string]$Path,
        [string]$Content,
        [string]$Name
    )
    $dir = Split-Path $Path -Parent
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    if ((Test-Path $Path) -and -not $Force) {
        Write-Warn2 "Exists (skipped): $Path"
        return
    }
    # Substitute the project name placeholder.
    $Content = $Content.Replace('__PROJECT_NAME__', $Name)
    # Write with UTF-8 (no BOM) and Unix line endings for portability.
    $Content = $Content -replace "`r`n", "`n"
    [System.IO.File]::WriteAllText($Path, $Content, (New-Object System.Text.UTF8Encoding($false)))
    Write-Ok "Wrote $Path"
}

function Add-FreeRTOSKernel {
    param([string]$ProjectDir)
    $target = Join-Path $ProjectDir 'FreeRTOS-Kernel'
    if (Test-Path (Join-Path $target 'portable\ThirdParty\GCC\RP2350_ARM_NTZ')) {
        Write-Ok "FreeRTOS-Kernel already present at $target"
        return
    }
    if (-not (Test-Command 'git')) {
        Write-Warn2 'Git not available. Clone FreeRTOS-Kernel manually into the project directory.'
        return
    }
    Write-Step "Cloning FreeRTOS-Kernel ($FREERTOS_KERNEL_BRANCH) into $target"
    $rc = Invoke-Native 'git' @('clone', '--depth', '1', '--branch', $FREERTOS_KERNEL_BRANCH, $FREERTOS_KERNEL_REPO, $target)
    if ($rc -ne 0) {
        Write-Warn2 "git clone FreeRTOS-Kernel failed (exit $rc). Fetch manually before building."
    }
}

function Add-InclFolder {
    param([string]$ProjectDir)
    $incl = Join-Path $ProjectDir 'incl'
    if (-not (Test-Path $incl)) {
        New-Item -ItemType Directory -Path $incl -Force | Out-Null
    }
    $keep = Join-Path $incl '.gitkeep'
    if (-not (Test-Path $keep)) {
        [System.IO.File]::WriteAllText($keep, '', (New-Object System.Text.UTF8Encoding($false)))
    }
    Write-Ok "Ensured incl\ folder at $incl"
}

function Update-ProjectCMake {
    param([string]$ProjectDir)

    $cmakePath = Join-Path $ProjectDir 'CMakeLists.txt'
    if (-not (Test-Path $cmakePath)) {
        throw "CMakeLists.txt not found at $cmakePath"
    }
    $incl = Join-Path $ProjectDir 'incl'
    if (-not (Test-Path $incl)) {
        Write-Warn2 "incl\ folder does not exist; creating empty one at $incl"
        New-Item -ItemType Directory -Path $incl -Force | Out-Null
    }

    # Discover user sources and header directories under incl\.
    $projRoot = (Resolve-Path $ProjectDir).Path.TrimEnd('\')
    function _RelPath($full) {
        $f = $full.TrimEnd('\')
        if ($f.StartsWith($projRoot, [StringComparison]::OrdinalIgnoreCase)) {
            return $f.Substring($projRoot.Length).TrimStart('\')
        }
        return $f
    }

    $sources = @(
        Get-ChildItem -Path $incl -Recurse -File -Filter '*.c' -ErrorAction SilentlyContinue |
            ForEach-Object { (_RelPath $_.FullName).Replace('\', '/') } |
            Sort-Object
    )
    $inclRoot = (Resolve-Path $incl).Path.TrimEnd('\')
    $headerDirs = @(
        Get-ChildItem -Path $incl -Recurse -File -Filter '*.h' -ErrorAction SilentlyContinue |
            ForEach-Object { $_.Directory.FullName.TrimEnd('\') } |
            Sort-Object -Unique |
            Where-Object { $_ -ne $inclRoot } |
            ForEach-Object { '${CMAKE_CURRENT_LIST_DIR}/' + (_RelPath $_).Replace('\', '/') }
    )

    $srcBlock = if ($sources.Count -gt 0) {
        ($sources | ForEach-Object { "    $_" }) -join "`n"
    } else { '' }

    $incBlock = if ($headerDirs.Count -gt 0) {
        ($headerDirs | ForEach-Object { "    $_" }) -join "`n"
    } else { '' }

    $text = [System.IO.File]::ReadAllText($cmakePath)

    $srcPattern = '(?s)(# === USER SOURCES BEGIN ===.*?\n)(.*?)(\s*# === USER SOURCES END ===)'
    $incPattern = '(?s)(# === USER INCLUDE DIRS BEGIN ===.*?\n)(.*?)(\s*# === USER INCLUDE DIRS END ===)'

    if ($text -notmatch $srcPattern) {
        throw 'USER SOURCES markers not found in CMakeLists.txt. Project was not created by this script or the markers were removed.'
    }
    if ($text -notmatch $incPattern) {
        throw 'USER INCLUDE DIRS markers not found in CMakeLists.txt.'
    }

    $newSrc = if ($srcBlock) { "`$1$srcBlock`n`$3" } else { "`$1`$3" }
    $newInc = if ($incBlock) { "`$1$incBlock`n`$3" } else { "`$1`$3" }

    $text = [regex]::Replace($text, $srcPattern, $newSrc)
    $text = [regex]::Replace($text, $incPattern, $newInc)

    [System.IO.File]::WriteAllText($cmakePath, $text, (New-Object System.Text.UTF8Encoding($false)))

    Write-Ok ("CMakeLists.txt updated: {0} source(s), {1} include dir(s)" -f $sources.Count, $headerDirs.Count)
    if ($sources.Count -gt 0) {
        Write-Host '  Sources:' -ForegroundColor Cyan
        $sources | ForEach-Object { Write-Host "    $_" }
    }
    if ($headerDirs.Count -gt 0) {
        Write-Host '  Include dirs:' -ForegroundColor Cyan
        $headerDirs | ForEach-Object { Write-Host "    $_" }
    }
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
$TargetPath = [System.IO.Path]::GetFullPath($TargetPath)

if ($Update) {
    if (-not (Test-Path $TargetPath)) {
        throw "Update mode: target path '$TargetPath' does not exist."
    }
    Write-Host ''
    Write-Host '============================================================' -ForegroundColor Magenta
    Write-Host 'BladeCore-M54C RTOS project update (rescan incl\)' -ForegroundColor Magenta
    Write-Host "  Target : $TargetPath" -ForegroundColor Magenta
    Write-Host '============================================================' -ForegroundColor Magenta
    Write-Host ''
    Update-ProjectCMake -ProjectDir $TargetPath
    return
}

if (-not $ProjectName) {
    $ProjectName = Split-Path $TargetPath -Leaf
}
if ($ProjectName -notmatch '^[A-Za-z_][A-Za-z0-9_]*$') {
    throw "ProjectName '$ProjectName' is not a valid C identifier."
}

Write-Host ''
Write-Host '============================================================' -ForegroundColor Magenta
Write-Host "BladeCore-M54C RP2354B RTOS project generator"                 -ForegroundColor Magenta
Write-Host "  Target : $TargetPath"                                        -ForegroundColor Magenta
Write-Host "  Name   : $ProjectName"                                       -ForegroundColor Magenta
Write-Host '============================================================' -ForegroundColor Magenta
Write-Host ''

if (Test-Path $TargetPath) {
    $entries = Get-ChildItem -Path $TargetPath -Force -ErrorAction SilentlyContinue
    if ($entries -and -not $Force) {
        throw "Target path '$TargetPath' is not empty. Use -Force to overwrite."
    }
} else {
    New-Item -ItemType Directory -Path $TargetPath -Force | Out-Null
}

if (-not $SkipToolInstall) {
    try {
        Install-AllTools
    } catch {
        Write-Fail "Tool installation failed: $_"
        Write-Warn2 'Continuing with project file generation.'
    }
} else {
    Write-Warn2 'Skipping tool detection/install (-SkipToolInstall).'
}

Write-Step 'Generating project files...'

Write-ProjectFile -Path (Join-Path $TargetPath 'main.c')                  -Content (Get-MainC)             -Name $ProjectName
Write-ProjectFile -Path (Join-Path $TargetPath 'CONFIG.h')                -Content (Get-ConfigH)           -Name $ProjectName
Write-ProjectFile -Path (Join-Path $TargetPath 'FreeRTOSConfig.h')        -Content (Get-FreeRTOSConfigH)   -Name $ProjectName
Write-ProjectFile -Path (Join-Path $TargetPath 'CMakeLists.txt')          -Content (Get-CMakeLists)        -Name $ProjectName
Write-ProjectFile -Path (Join-Path $TargetPath 'pico_sdk_import.cmake')   -Content (Get-PicoSdkImport)     -Name $ProjectName
Write-ProjectFile -Path (Join-Path $TargetPath 'build.py')                -Content (Get-BuildPy)           -Name $ProjectName
Write-ProjectFile -Path (Join-Path $TargetPath '.gitignore')              -Content (Get-GitIgnore)         -Name $ProjectName

$vs = Join-Path $TargetPath '.vscode'
Write-ProjectFile -Path (Join-Path $vs 'cmake-kits.json')       -Content (Get-VscodeCmakeKits)      -Name $ProjectName
Write-ProjectFile -Path (Join-Path $vs 'c_cpp_properties.json') -Content (Get-VscodeCppProperties)  -Name $ProjectName
Write-ProjectFile -Path (Join-Path $vs 'extensions.json')       -Content (Get-VscodeExtensions)     -Name $ProjectName
Write-ProjectFile -Path (Join-Path $vs 'launch.json')           -Content (Get-VscodeLaunch)         -Name $ProjectName
Write-ProjectFile -Path (Join-Path $vs 'settings.json')         -Content (Get-VscodeSettings)       -Name $ProjectName
Write-ProjectFile -Path (Join-Path $vs 'tasks.json')            -Content (Get-VscodeTasks)          -Name $ProjectName

Add-InclFolder      -ProjectDir $TargetPath
Add-FreeRTOSKernel  -ProjectDir $TargetPath

# Pick whichever real Python command exists for the "Next steps" hint.
$pyReal = Get-RealPythonCommand
$pyHint = if ($pyReal) { $pyReal.Name } else { 'python' }

Write-Host ''
Write-Ok "Project '$ProjectName' created at $TargetPath"
Write-Host ''
Write-Host 'Next steps:' -ForegroundColor Cyan
Write-Host '  1. Open the folder in VS Code:' -ForegroundColor Cyan
Write-Host "       code `"$TargetPath`"" -ForegroundColor White
Write-Host '  2. Build from a fresh terminal (env vars are set at user scope):' -ForegroundColor Cyan
Write-Host "       cd `"$TargetPath`"; $pyHint build.py" -ForegroundColor White
Write-Host '  3. Flash (BOOTSEL button held while plugging USB):' -ForegroundColor Cyan
Write-Host "       $pyHint build.py upload" -ForegroundColor White
Write-Host ''
